# Handling Missing data

### There are 4 methods to identify treat missing data:
#### isnull(): Indicates the presence of missing values and returns boolean
#### notnull(): opposite of isnull() return boolean
#### dropna(): drops the missing values from a dataframe and returns the rest
#### fillna(): fills(or imputes)the missing values by specific values

In [60]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np

In [61]:
df = pd.read_csv("C:\\Users\\SHIVBASAV\\Downloads\\house_data.csv")
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,03-09-2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra,-37.8014,144.9958,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,03-12-2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,04-02-2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,04-02-2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra,-37.8114,145.0116,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,04-03-2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0

In [62]:
print(df.shape)
print(df.info())

(23547, 21)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23547 entries, 0 to 23546
Data columns (total 21 columns):
Suburb           23547 non-null object
Address          23547 non-null object
Rooms            23547 non-null int64
Type             23547 non-null object
Price            18396 non-null float64
Method           23547 non-null object
SellerG          23547 non-null object
Date             23547 non-null object
Distance         23546 non-null float64
Postcode         23546 non-null float64
Bedroom2         19066 non-null float64
Bathroom         19063 non-null float64
Car              18921 non-null float64
Landsize         17410 non-null float64
BuildingArea     10018 non-null float64
YearBuilt        11540 non-null float64
CouncilArea      15656 non-null object
Lattitude        19243 non-null float64
Longtitude       19243 non-null float64
Regionname       23546 non-null object
Propertycount    23546 non-null float64
dtypes: float64(12), int64(1), object(8)
memory usage: 3.8+ MB
None

## Identifying missing values
#### The methods isnull() and notnull() are the most common ways of identifying missing values
#### While handling the missing data, you first need to identify the rows and columns containing missing values, count the number of missing values, and then decide how you want to treat them.
#### It is important that you treat the missing values in each column seperately, rather than implementing a single solution(e.g. replacing NaN's with the mean of the cloumn)for all cloumns
#### isnull() returns a boolean value which can be used to fill the rows or columns containing missing values

In [63]:
df.isnull()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,False,False,False,False,True,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,True,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
9,False,False,False,False,True,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,False,False
16,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,False,False
17,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,False,False
20,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,False,False
22,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,False,False
23,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,False,False
28,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23517,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,True,False,False,False,False
23518,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,True,False,False,False,False
23519,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,True,False,False,False,False
23520,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
23521,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
23522,False,False,False,False,True,False,False,False,False,False,...,False,False,False,True,True,True,False,False,False,False
23523,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,True,False,False,False,False
23524,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,True,False,False,False,False
23525,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
23526,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,True,False,False,False,False
23527,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
23528,False,False,False,False,True,False,False,False,False,False,...,False,False,True,True,True,True,False,False,False,False
23529,False,False,False,False,True,False,False,False,False,False,...,False,False,False,True,True,True,False,False,False,False
23530,False,False,False,False,True,False,False,False,False,False,...,False,False,True,True,True,True,False,False,False,False
23531,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,False,False
23532,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
23533,False,False,False,False,True,False,False,False,False,False,...,False,False,True,True,True,True,False,False,False,False
23534,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,True,False,False,False,False
23535,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,True,False,False,False,False
23536,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,True,True,False,False,False,False
23537,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,True,False,False,False,False
23538,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
23539,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,True,False,False,False,False
23540,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,True,False,False,False,False
23541,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
23542,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
23543,False,False,False,False,True,False,False,False,False,False,...,True,True,True,True,True,True,False,False,False,False
23544,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,True,True,False,False,False,False
23545,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
23546,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,True,False,False,False,False

In [64]:
df.notnull()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,True,True,True,True,False,True,True,True,True,True,...,True,True,True,False,False,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,False,False,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,False,True,True,True,True,True,...,True,True,True,False,False,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
5,True,True,True,True,True,True,True,True,True,True,...,True,True,True,False,False,True,True,True,True,True
6,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
7,True,True,True,True,False,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
8,True,True,True,True,False,True,True,True,True,True,...,True,True,True,False,True,True,True,True,True,True
9,True,True,True,True,False,True,True,True,True,True,...,True,True,True,False,True,True,True,True,True,True
10,True,True,True,True,True,True,True,True,True,True,...,True,True,True,False,False,True,True,True,True,True
11,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
12,True,True,True,True,False,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
13,True,True,True,True,False,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
14,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
15,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,True,True
16,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,True,True
17,True,True,True,True,True,True,True,True,True,True,...,True,True,True,False,False,True,True,True,True,True
18,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
19,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,True,True
20,True,True,True,True,False,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
21,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,True,True
22,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,True,True
23,True,True,True,True,True,True,True,True,True,True,...,True,True,True,False,False,True,True,True,True,True
24,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
25,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
26,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,True,True,True,True
27,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,True,True
28,True,True,True,True,True,True,True,True,True,True,...,True,True,True,False,False,True,True,True,True,True
29,True,True,True,True,True,True,True,True,True,True,...,True,True,True,False,False,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23517,True,True,True,True,True,True,True,True,True,True,...,True,True,False,True,True,False,True,True,True,True
23518,True,True,True,True,True,True,True,True,True,True,...,True,True,True,False,False,False,True,True,True,True
23519,True,True,True,True,True,True,True,True,True,True,...,True,True,True,False,False,False,True,True,True,True
23520,True,True,True,True,False,True,True,True,True,True,...,True,True,True,True,True,False,True,True,True,True
23521,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,False,True,True,True,True
23522,True,True,True,True,False,True,True,True,True,True,...,True,True,True,False,False,False,True,True,True,True
23523,True,True,True,True,True,True,True,True,True,True,...,True,True,True,False,False,False,True,True,True,True
23524,True,True,True,True,True,True,True,True,True,True,...,True,True,True,False,False,False,True,True,True,True
23525,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,False,True,True,True,True
23526,True,True,True,True,True,True,True,True,True,True,...,True,True,False,True,True,False,True,True,True,True
23527,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,False,True,True,True,True
23528,True,True,True,True,False,True,True,True,True,True,...,True,True,False,False,False,False,True,True,True,True
23529,True,True,True,True,False,True,True,True,True,True,...,True,True,True,False,False,False,True,True,True,True
23530,True,True,True,True,False,True,True,True,True,True,...,True,True,False,False,False,False,True,True,True,True
23531,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,True,True
23532,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,False,True,True,True,True
23533,True,True,True,True,False,True,True,True,True,True,...,True,True,False,False,False,False,True,True,True,True
23534,True,True,True,True,True,True,True,True,True,True,...,True,True,False,True,True,False,True,True,True,True
23535,True,True,True,True,True,True,True,True,True,True,...,True,True,True,False,False,False,True,True,True,True
23536,True,True,True,True,True,True,True,True,True,True,...,True,True,False,False,False,False,True,True,True,True
23537,True,True,True,True,True,True,True,True,True,True,...,True,True,True,False,True,False,True,True,True,True
23538,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,False,True,True,True,True
23539,True,True,True,True,True,True,True,True,True,True,...,True,True,True,False,True,False,True,True,True,True
23540,True,True,True,True,True,True,True,True,True,True,...,True,True,False,True,True,False,True,True,True,True
23541,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,False,True,True,True,True
23542,True,True,True,True,False,True,True,True,True,True,...,True,True,True,True,True,False,True,True,True,True
23543,True,True,True,True,False,True,True,True,True,True,...,False,False,False,False,False,False,True,True,True,True
23544,True,True,True,True,True,True,True,True,True,True,...,True,True,False,False,False,False,True,True,True,True
23545,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,False,True,True,True,True
23546,True,True,True,True,True,True,True,True,True,True,...,True,True,False,True,True,False,True,True,True,True

In [65]:
df.isnull().sum()
#summing up missing values(col wise)

Suburb               0
Address              0
Rooms                0
Type                 0
Price             5151
Method               0
SellerG              0
Date                 0
Distance             1
Postcode             1
Bedroom2          4481
Bathroom          4484
Car               4626
Landsize          6137
BuildingArea     13529
YearBuilt        12007
CouncilArea       7891
Lattitude         4304
Longtitude        4304
Regionname           1
Propertycount        1
dtype: int64

#### the funcyions any() and all() are quite usefull to identify rows and columns having missing values:
##### any() returns True when at least one value satisfies a condition(equilent to logical or)
#####  all() returns True when all the values satisfy a condition (equilent it logical and)

In [66]:
df.isnull().any()

Suburb           False
Address          False
Rooms            False
Type             False
Price             True
Method           False
SellerG          False
Date             False
Distance          True
Postcode          True
Bedroom2          True
Bathroom          True
Car               True
Landsize          True
BuildingArea      True
YearBuilt         True
CouncilArea       True
Lattitude         True
Longtitude        True
Regionname        True
Propertycount     True
dtype: bool

In [67]:
df.isnull().all()

Suburb           False
Address          False
Rooms            False
Type             False
Price            False
Method           False
SellerG          False
Date             False
Distance         False
Postcode         False
Bedroom2         False
Bathroom         False
Car              False
Landsize         False
BuildingArea     False
YearBuilt        False
CouncilArea      False
Lattitude        False
Longtitude       False
Regionname       False
Propertycount    False
dtype: bool

# Identifying missing values in rows

In [68]:
df.isnull().any(axis=1)

0         True
1         True
2        False
3         True
4        False
5         True
6        False
7         True
8         True
9         True
10        True
11       False
12        True
13        True
14       False
15        True
16        True
17        True
18       False
19        True
20        True
21        True
22        True
23        True
24       False
25       False
26        True
27        True
28        True
29        True
         ...
23517     True
23518     True
23519     True
23520     True
23521     True
23522     True
23523     True
23524     True
23525     True
23526     True
23527     True
23528     True
23529     True
23530     True
23531     True
23532     True
23533     True
23534     True
23535     True
23536     True
23537     True
23538     True
23539     True
23540     True
23541     True
23542     True
23543     True
23544     True
23545     True
23546     True
Length: 23547, dtype: bool

In [69]:
df.isnull().all(axis=1).sum()

0

In [70]:
df.isnull().sum(axis=1)

0        3
1        2
2        0
3        3
4        0
5        2
6        0
7        1
8        2
9        2
10       2
11       0
12       1
13       1
14       0
15       9
16       9
17       2
18       0
19       9
20       1
21       9
22       9
23       2
24       0
25       0
26       7
27       9
28       2
29       2
        ..
23517    2
23518    3
23519    3
23520    2
23521    1
23522    4
23523    3
23524    3
23525    1
23526    2
23527    1
23528    5
23529    4
23530    5
23531    9
23532    1
23533    5
23534    2
23535    3
23536    4
23537    2
23538    1
23539    2
23540    2
23541    1
23542    2
23543    8
23544    4
23545    1
23546    2
Length: 23547, dtype: int64

# Treating missing values

In [71]:
# There are broadly two ways of treating missing values:
#1. Delete: Delete the missing values
#2. Impute:
#         Imputing by a simple statistic: Reaplacing the missing value by another value, commonly the mean, meadian, mode etc
#         Predictive techniques: Use statistical models such as K-NN, SVM etc to predict and impute missing values
# In general imputation makes assumptions about the missing values

In [72]:
round(100*(df.isnull().sum()/len(df.index)),2)

Suburb            0.00
Address           0.00
Rooms             0.00
Type              0.00
Price            21.88
Method            0.00
SellerG           0.00
Date              0.00
Distance          0.00
Postcode          0.00
Bedroom2         19.03
Bathroom         19.04
Car              19.65
Landsize         26.06
BuildingArea     57.46
YearBuilt        50.99
CouncilArea      33.51
Lattitude        18.28
Longtitude       18.28
Regionname        0.00
Propertycount     0.00
dtype: float64

In [73]:
df=df.drop('BuildingArea',axis=1)
df=df.drop('YearBuilt',axis=1)
df=df.drop('CouncilArea',axis=1)

round(100*(df.isnull().sum()/len(df.index)),2)

Suburb            0.00
Address           0.00
Rooms             0.00
Type              0.00
Price            21.88
Method            0.00
SellerG           0.00
Date              0.00
Distance          0.00
Postcode          0.00
Bedroom2         19.03
Bathroom         19.04
Car              19.65
Landsize         26.06
Lattitude        18.28
Longtitude       18.28
Regionname        0.00
Propertycount     0.00
dtype: float64

In [74]:
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,03-09-2016,2.5,3067.0,2.0,1.0,1.0,126.0,-37.80140,144.99580,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,03-12-2016,2.5,3067.0,2.0,1.0,1.0,202.0,-37.79960,144.99840,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,04-02-2016,2.5,3067.0,2.0,1.0,0.0,156.0,-37.80790,144.99340,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,04-02-2016,2.5,3067.0,3.0,2.0,1.0,0.0,-37.81140,145.01160,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,04-03-2017,2.5,3067.0,3.0,2.0,0.0,134.0,-37.80930,144.99440,Northern Metropolitan,4019.0
5,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,04-03-2017,2.5,3067.0,3.0,2.0,1.0,94.0,-37.79690,144.99690,Northern Metropolitan,4019.0
6,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,04-06-2016,2.5,3067.0,3.0,1.0,2.0,120.0,-37.80720,144.99410,Northern Metropolitan,4019.0
7,Abbotsford,16 Maugie St,4,h,NaN,SN,Nelson,06-08-2016,2.5,3067.0,3.0,2.0,2.0,400.0,-37.79650,144.99650,Northern Metropolitan,4019.0
8,Abbotsford,53 Turner St,2,h,NaN,S,Biggin,06-08-2016,2.5,3067.0,4.0,1.0,2.0,201.0,-37.79950,144.99740,Northern Metropolitan,4019.0
9,Abbotsford,99 Turner St,2,h,NaN,S,Collins,06-08-2016,2.5,3067.0,3.0,2.0,1.0,202.0,-37.79960,144.99890,Northern Metropolitan,4019.0
10,Abbotsford,129 Charles St,2,h,941000.0,S,Jellis,07-05-2016,2.5,3067.0,2.0,1.0,0.0,181.0,-37.80410,144.99530,Northern Metropolitan,4019.0
11,Abbotsford,124 Yarra St,3,h,1876000.0,S,Nelson,07-05-2016,2.5,3067.0,4.0,2.0,0.0,245.0,-37.80240,144.99930,Northern Metropolitan,4019.0
12,Abbotsford,121/56 Nicholson St,2,u,NaN,PI,Biggin,07-11-2016,2.5,3067.0,2.0,2.0,1.0,4292.0,-37.80780,144.99650,Northern Metropolitan,4019.0
13,Abbotsford,17 Raphael St,4,h,NaN,W,Biggin,07-11-2016,2.5,3067.0,6.0,2.0,0.0,230.0,-37.80660,144.99360,Northern Metropolitan,4019.0
14,Abbotsford,98 Charles St,2,h,1636000.0,S,Nelson,08-10-2016,2.5,3067.0,2.0,1.0,2.0,256.0,-37.80600,144.99540,Northern Metropolitan,4019.0
15,Abbotsford,217 Langridge St,3,h,1000000.0,S,Jellis,08-10-2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
16,Abbotsford,18a Mollison St,2,t,745000.0,S,Jellis,08-10-2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
17,Abbotsford,6/241 Nicholson St,1,u,300000.0,S,Biggin,08-10-2016,2.5,3067.0,1.0,1.0,1.0,0.0,-37.80080,144.99730,Northern Metropolitan,4019.0
18,Abbotsford,10 Valiant St,2,h,1097000.0,S,Biggin,08-10-2016,2.5,3067.0,3.0,1.0,2.0,220.0,-37.80100,144.99890,Northern Metropolitan,4019.0
19,Abbotsford,403/609 Victoria St,2,u,542000.0,S,Dingle,08-10-2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
20,Abbotsford,2 Rich St,2,h,NaN,SP,Biggin,10-12-2016,2.5,3067.0,2.0,1.0,1.0,176.0,-37.79980,144.99720,Northern Metropolitan,4019.0
21,Abbotsford,25/84 Trenerry Cr,2,u,760000.0,SP,Biggin,10-12-2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
22,Abbotsford,106/119 Turner St,1,u,481000.0,SP,Purplebricks,10-12-2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
23,Abbotsford,411/8 Grosvenor St,2,u,700000.0,VB,Jellis,12-11-2016,2.5,3067.0,2.0,2.0,1.0,0.0,-37.81100,145.00670,Northern Metropolitan,4019.0
24,Abbotsford,40 Nicholson St,3,h,1350000.0,VB,Nelson,12-11-2016,2.5,3067.0,3.0,2.0,2.0,214.0,-37.80850,144.99640,Northern Metropolitan,4019.0
25,Abbotsford,123/56 Nicholson St,2,u,750000.0,S,Biggin,12-11-2016,2.5,3067.0,2.0,2.0,1.0,0.0,-37.80780,144.99650,Northern Metropolitan,4019.0
26,Abbotsford,22 Park St,4,h,1985000.0,S,Biggin,12-11-2016,2.5,3067.0,NaN,NaN,NaN,NaN,-37.80840,144.99420,Northern Metropolitan,4019.0
27,Abbotsford,13/84 Trenerry Cr,1,u,500000.0,S,Biggin,12-11-2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
28,Abbotsford,45 William St,2,h,1172500.0,S,Biggin,13-08-2016,2.5,3067.0,2.0,1.0,1.0,195.0,-37.80840,144.99730,Northern Metropolitan,4019.0
29,Abbotsford,7/20 Abbotsford St,1,u,441000.0,SP,Greg,14-05-2016,2.5,3067.0,1.0,1.0,1.0,0.0,-37.80160,144.99880,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23517,Vermont South,2 Settlers Ct,4,h,1295000.0,SP,Purplebricks,26-08-2017,17.2,3133.0,4.0,2.0,2.0,NaN,-37.85928,145.18715,Eastern Metropolitan,4280.0
23518,Vermont South,9 Winswood Cl,4,h,1250000.0,PI,Philip,26-08-2017,17.2,3133.0,4.0,2.0,2.0,986.0,-37.84679,145.20051,Eastern Metropolitan,4280.0
23519,Viewbank,149 Graham Rd,5,h,1316000.0,SP,Nelson,26-08-2017,8.9,3084.0,5.0,3.0,3.0,696.0,-37.73501,145.08341,Eastern Metropolitan,2698.0
23520,Viewbank,7 Northwood Dr,4,h,NaN,SP,Nelson,26-08-2017,8.9,3084.0,4.0,2.0,2.0,1105.0,-37.73703,145.09392,Eastern Metropolitan,2698.0
23521,Wantirna,16 chesterfield Ct,4,h,951000.0,S,Ray,26-08-2017,14.7,3152.0,4.0,2.0,2.0,704.0,-37.85639,145.23536,Eastern Metropolitan,5424.0
23522,Wantirna,9 eton Sq,4,h,NaN,PI,Ray,26-08-2017,14.7,3152.0,4.0,2.0,3.0,785.0,-37.85297,145.23815,Eastern Metropolitan,5424.0
23523,Wantirna South,12 Armagh Cr,4,h,1323000.0,S,Barry,26-08-2017,14.7,3152.0,4.0,2.0,2.0,551.0,-37.87608,145.22390,Eastern Metropolitan,7082.0
23524,Wantirna South,34 Fewster Dr,3,h,970000.0,S,Barry,26-08-2017,14.7,3152.0,3.0,2.0,2.0,674.0,-37.88360,145.22805,Eastern Metropolitan,7082.0
23525,Wantirna South,15 Mara Cl,4,h,1330000.0,S,Barry,26-08-2017,14.7,3152.0,4.0,2.0,2.0,717.0,-37.86887,145.22116,Eastern Metropolitan,7082.0
23526,Watsonia,2/14 Daours Ct,2,u,590000.0,S,Lindellas,26-08-2017,14.5,3087.0,2.0,1.0,1.0,NaN,-37.71500,145.07649,Northern Metropolitan,2329.0
23527,Watsonia,76 Kenmare St,2,h,650000.0,PI,Morrison,26-08-2017,14.5,3087.0,2.0,1.0,1.0,210.0,-37.70657,145.07878,Northern Metropolitan,2329.0
23528,Watsonia North,22 Meakin St,3,h,NaN,PI,Nelson,26-08-2017,14.5,3087.0,3.0,2.0,3.0,NaN,-37.70186,145.08635,Northern Metropolitan,1442.0
23529,Werribee,6 Feijoa Ct,5,h,NaN,W,YPA,26-08-2017,14.7,3030.0,5.0,3.0,2.0,535.0,-37.89362,144.66767,Western Metropolitan,16166.0
23530,Werribee,11 Gundaroo Sq,4,h,NaN,PI,Stockdale,26-08-2017,14.7,3030.0,4.0,2.0,6.0,NaN,-37.91230,144.66980,Western Metropolitan,16166.0
23531,Werribee,91 Latham St,4,h,540000.0,PI,Triwest,26-08-2017,14.7,3030.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,16166.0
23532,Werribee,5 Nuragi Ct,4,h,635000.0,S,hockingstuart,26-08-2017,14.7,3030.0,4.0,2.0,1.0,662.0,-37.89327,144.64789,Western Metropolitan,16166.0
23533,Werribee,3 Sky Ct,3,h,NaN,PI,Barry,26-08-2017,14.7,3030.0,3.0,2.0,2.0,NaN,-37.89096,144.64200,Western Metropolitan,16166.0
23534,West Footscray,1/21 Waratah St,2,t,655000.0,S,Jas,26-08-2017,6.4,3012.0,2.0,2.0,1.0,NaN,-37.80968,144.86819,Western Metropolitan,5058.0
23535,Westmeadows,9 Black St,3,h,582000.0,S,Red,26-08-2017,16.5,3049.0,3.0,2.0,2.0,256.0,-37.67917,144.89390,Northern Metropolitan,2474.0
23536,Westmeadows,81 Hillcrest Dr,4,h,720000.0,VB,Barry,26-08-2017,16.5,3049.0,4.0,2.0,0.0,NaN,-37.68006,144.87550,Northern Metropolitan,2474.0
23537,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26-08-2017,16.7,3150.0,4.0,2.0,2.0,652.0,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
23538,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26-08-2017,6.8,3016.0,3.0,2.0,2.0,333.0,-37.85927,144.87904,Western Metropolitan,6380.0
23539,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26-08-2017,6.8,3016.0,3.0,2.0,4.0,436.0,-37.85274,144.88738,Western Metropolitan,6380.0
23540,Williamstown,8/2 Thompson St,2,t,622500.0,SP,Greg,26-08-2017,6.8,3016.0,2.0,2.0,1.0,NaN,-37.86393,144.90484,Western Metropolitan,6380.0
23541,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26-08-2017,6.8,3016.0,4.0,1.0,5.0,866.0,-37.85908,144.89299,Western Metropolitan,6380.0
23542,Wyndham Vale,25 Clitheroe Dr,3,u,NaN,PN,Harcourts,26-08-2017,27.2,3024.0,3.0,1.0,0.0,552.0,-37.90032,144.61839,Western Metropolitan,5262.0
23543,Wyndham Vale,19 Dalrymple Bvd,4,h,NaN,S,hockingstuart,26-08-2017,27.2,3024.0,NaN,NaN,NaN,NaN,-37.87882,144.60184,Western Metropolitan,5262.0
23544,Yallambie,17 Amaroo Wy,4,h,1100000.0,S,Buckingham,26-08-2017,12.7,3085.0,4.0,3.0,2.0,NaN,-37.72006,145.10547,Northern Metropolitan,1369.0
23545,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26-08-2017,6.3,3013.0,4.0,1.0,1.0,362.0,-37.81188,144.88449,Western Metropolitan,6543.0
23546,Yarraville,33 Freeman St,4,h,1050000.0,VB,Village,26-08-2017,6.3,3013.0,4.0,2.0,2.0,NaN,-37.81829,144.87404,Western Metropolitan,6543.0

In [75]:
df=df[df.isnull().sum(axis=1)<=5]
round(100*(df.isnull().sum()/len(df.index)),2)

Suburb            0.00
Address           0.00
Rooms             0.00
Type              0.00
Price            21.71
Method            0.00
SellerG           0.00
Date              0.00
Distance          0.00
Postcode          0.00
Bedroom2          1.05
Bathroom          1.07
Car               1.81
Landsize          9.65
Lattitude         0.13
Longtitude        0.13
Regionname        0.00
Propertycount     0.00
dtype: float64

In [76]:
df[df.isnull().sum(axis=1)>5].shape

(0, 18)

In [77]:
len(df[df.isnull().sum(axis=1)>5].index)

0

In [78]:
round(100*(df.isnull().sum()/len(df.index)),2)

Suburb            0.00
Address           0.00
Rooms             0.00
Type              0.00
Price            21.71
Method            0.00
SellerG           0.00
Date              0.00
Distance          0.00
Postcode          0.00
Bedroom2          1.05
Bathroom          1.07
Car               1.81
Landsize          9.65
Lattitude         0.13
Longtitude        0.13
Regionname        0.00
Propertycount     0.00
dtype: float64

In [79]:
df=df[~np.isnan(df['Price'])]

In [80]:
round(100*(df.isnull().sum()/len(df.index)),2)

Suburb           0.00
Address          0.00
Rooms            0.00
Type             0.00
Price            0.00
Method           0.00
SellerG          0.00
Date             0.00
Distance         0.00
Postcode         0.00
Bedroom2         1.05
Bathroom         1.07
Car              1.76
Landsize         9.83
Lattitude        0.15
Longtitude       0.15
Regionname       0.00
Propertycount    0.00
dtype: float64

In [81]:
df.shape

(15086, 18)

In [87]:
#remoc=ving NaN price rows
df=df[~np.isnan(df['Landsize'])]

In [84]:
round(100*(df.isnull().sum()/len(df.index)),2)

Suburb           0.00
Address          0.00
Rooms            0.00
Type             0.00
Price            0.00
Method           0.00
SellerG          0.00
Date             0.00
Distance         0.00
Postcode         0.00
Bedroom2         0.00
Bathroom         0.01
Car              0.46
Landsize         0.00
Lattitude        0.16
Longtitude       0.16
Regionname       0.00
Propertycount    0.00
dtype: float64

In [86]:
df.shape

(13603, 18)

In [88]:
df.size

244854

In [90]:
df.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,Lattitude,Longtitude,Propertycount
count,13603.000000,1.360300e+04,13603.000000,13603.000000,13603.000000,13602.000000,13540.000000,13603.000000,13581.000000,13581.000000,13603.000000
mean,2.938175,1.075338e+06,10.140469,3105.308094,2.914945,1.534921,1.610414,558.116371,-37.809204,144.995221,7451.025583
std,0.955986,6.389857e+05,5.871805,90.808664,0.966145,0.691834,0.962244,3987.326586,0.079257,0.103913,4378.442541
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,-38.182550,144.431810,249.000000
25%,2.000000,6.500000e+05,6.100000,3044.000000,2.000000,1.000000,1.000000,176.500000,-37.856820,144.929600,4380.000000
50%,3.000000,9.030000e+05,9.200000,3084.000000,3.000000,1.000000,2.000000,440.000000,-37.802360,145.000100,6543.000000
75%,3.000000,1.330000e+06,13.000000,3148.000000,3.000000,2.000000,2.000000,651.000000,-37.756400,145.058320,10331.000000
max,10.000000,9.000000e+06,48.100000,3977.000000,20.000000,8.000000,10.000000,433014.000000,-37.408530,145.526350,21650.000000